// 食物
export default [
    {"type": "node", "node0": "", "node": "", "code": "c0", "text": "1. 主食"},
    {"type": "leaf", "node0": "", "node": "c0", "code": "c0c0", "text": "米饭"},
    {"type": "leaf", "node0": "", "node": "c0", "code": "c0c1", "text": "稀饭或泡饭"},
    {"type": "leaf", "node0": "", "node": "c0", "code": "c0c2", "text": "面条"},
    {"type": "leaf", "node0": "", "node": "c0", "code": "c0c3", "text": "馄饨或饺子"},
    {"type": "leaf", "node0": "", "node": "c0", "code": "c0c4", "text": "馒头"},
    {"type": "leaf", "node0": "", "node": "c0", "code": "c0c5", "text": "肉包"},
    {"type": "leaf", "node0": "", "node": "c0", "code": "c0c6", "text": "菜包"},
    {"type": "leaf", "node0": "", "node": "c0", "code": "c0c7", "text": "油饼类"},
    {"type": "leaf", "node0": "", "node": "c0", "code": "c0c8", "text": "面包或蛋糕"},

    {"type": "node", "node0": "", "node": "", "code": "c1", "text": "2. 菜类"},
    {"type": "leaf", "node0": "", "node": "c1", "code": "c1c0", "text": "蛋类"},
    {"type": "leaf", "node0": "", "node": "c1", "code": "c1c1", "text": "大荤类如鸡鸭鱼"},
    {"type": "leaf", "node0": "", "node": "c1", "code": "c1c2", "text": "小荤类如豌豆肉"},
    {"type": "leaf", "node0": "", "node": "c1", "code": "c1c3", "text": "蛋类如番茄炒蛋"},
    {"type": "leaf", "node0": "", "node": "c1", "code": "c1c4", "text": "水产类如鱼、虾"},
    {"type": "leaf", "node0": "", "node": "c1", "code": "c1c5", "text": "素菜类如青菜"},

    {"type": "node", "node0": "", "node": "", "code": "c2", "text": "3. 水果类"},
    {"type": "leaf", "node0": "", "node": "c2", "code": "c2c0", "text": "浆果如番茄、葡萄"},
    {"type": "leaf", "node0": "", "node": "c2", "code": "c2c1", "text": "瓜果类如西瓜、哈密瓜"},
    {"type": "leaf", "node0": "", "node": "c2", "code": "c2c2", "text": "橘果类如柑橘、橙子"},
    {"type": "leaf", "node0": "", "node": "c2", "code": "c2c3", "text": "仁果类如苹果、梨"},
    {"type": "leaf", "node0": "", "node": "c2", "code": "c2c4", "text": "核果类如桃、李"},
    {"type": "leaf", "node0": "", "node": "c2", "code": "c2c5", "text": "热带类如菠萝、香蕉"},

    {"type": "node", "node0": "", "node": "", "code": "c3", "text": "4. 坚果、果干类"},
    {"type": "leaf", "node0": "", "node": "c3", "code": "c3c0", "text": "坚果类"},
    {"type": "leaf", "node0": "", "node": "c3", "code": "c3c1", "text": "果干类"},
    {"type": "leaf", "node0": "", "node": "c3", "code": "c3c2", "text": "混合坚果果干"},

    {"type": "node", "node0": "", "node": "", "code": "c4", "text": "5. 酒水饮料类"},
    {"type": "node", "node0": "", "node": "c4", "code": "c4c0", "text": "5.1. 饮料类"},
    {"type": "leaf", "node0": "c4c0", "node": "c4", "code": "c4c0c0", "text": "碳酸饮料类"},
    {"type": "leaf", "node0": "c4c0", "node": "c4", "code": "c4c0c1", "text": "茶饮料"},
    {"type": "leaf", "node0": "c4c0", "node": "c4", "code": "c4c0c2", "text": "果汁/果味饮料"},
    {"type": "leaf", "node0": "c4c0", "node": "c4", "code": "c4c0c3", "text": "功能性饮料"},
    {"type": "leaf", "node0": "c4c0", "node": "c4", "code": "c4c0c4", "text": "蛋白饮料如椰汁，花生牛奶"},
    {"type": "leaf", "node0": "c4c0", "node": "c4", "code": "c4c0c5", "text": "纯净水"},
    {"type": "leaf", "node0": "c4c0", "node": "c4", "code": "c4c0c6", "text": "苏打/气泡水"},
    {"type": "leaf", "node0": "c4c0", "node": "c4", "code": "c4c0c7", "text": "矿泉水"},
    {"type": "leaf", "node0": "c4c0", "node": "c4", "code": "c4c0c8", "text": "鲜奶类"},
    {"type": "leaf", "node0": "c4c0", "node": "c4", "code": "c4c0c9", "text": "咖啡"},

    {"type": "node", "node0": "", "node": "c4", "code": "c4c1", "text": "5.2. 茶水类"},
    {"type": "leaf", "node0": "c4c1", "node": "c4", "code": "c4c1c0", "text": "红茶"},
    {"type": "leaf", "node0": "c4c1", "node": "c4", "code": "c4c1c1", "text": "绿茶"},
    {"type": "leaf", "node0": "c4c1", "node": "c4", "code": "c4c1c2", "text": "黄茶"},
    {"type": "leaf", "node0": "c4c1", "node": "c4", "code": "c4c1c3", "text": "乌龙茶"},
    {"type": "leaf", "node0": "c4c1", "node": "c4", "code": "c4c1c4", "text": "黑茶"},
    {"type": "leaf", "node0": "c4c1", "node": "c4", "code": "c4c1c5", "text": "白茶"},

    {"type": "node", "node0": "", "node": "c4", "code": "c4c2", "text": "5.3. 酒水类"},
    {"type": "leaf", "node0": "c4c2", "node": "c4", "code": "c4c2c0", "text": "啤酒类"},
    {"type": "leaf", "node0": "c4c2", "node": "c4", "code": "c4c2c1", "text": "预调酒如RIO"},
    {"type": "leaf", "node0": "c4c2", "node": "c4", "code": "c4c2c2", "text": "白酒/黄酒"},
    {"type": "leaf", "node0": "c4c2", "node": "c4", "code": "c4c2c3", "text": "葡萄酒"}
]