export default {
    "ly0d10unit": {
        "_id": {"note": "工作单位", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "name": {"note": "工作单位名称", "type": "string", "required": "true"},
        "wx_appid": {"note": "微信支付 - APPID", "type": "string"},
        "wx_mchid": {"note": "微信商户号", "type": "string"}
    },
    "ly0d10group": {
        "_id": {"note": "工作组", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d10unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "工作单位名称", "type": "string", "required": "true"},
        "name": {"note": "工作组名称", "type": "string", "required": "true"}
    },
    "ly0d10worker": {
        "_id": {"note": "工作人员信息", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d10unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "工作单位名称", "type": "string", "required": "true"},
        "id_group": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d10group", "ref_fldName": "_id", "required": "true"},
        "group_name": {"note": "工作组名称", "type": "string", "required": "true"},
        "cellphone": {"note": "手机号", "type": "string", "required": "true"},
        "name": {"note": "姓名", "type": "string", "required": "true"},
        "idno": {"note": "身份证号", "type": "string", "required": "true"},
        "sex_code": {"note": "性别", "type": "string", "required": "true"},
        "sex_text": {"note": "", "type": "string", "required": "true"},
        "birthyear": {"note": "出生年份", "type": "integer", "required": "true"},
        "photo": {"note": "照片", "type": "string"}
    },
    "ly0d10service": {
        "_id": {"note": "服务项目", "type": "mongodb.id", "required": "true"}
    },
    "ly0d10business": {
        "_id": {"note": "客户工单", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d10unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "工作单位名称", "type": "string", "required": "true"},
        "id_group": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d10group", "ref_fldName": "_id", "required": "true"},
        "group_name": {"note": "工作组名称", "type": "string", "required": "true"},
        "id_worker": {"note": "工作人员信息", "type": "mongodb.id", "ref_tblName": "ly0d10worker", "ref_fldName": "_id", "required": "true"},
        "worker_cellphone": {"note": "工作人员手机号", "type": "string", "required": "true"},
        "worker_name": {"note": "工作人员姓名", "type": "string", "required": "true"},
        "worker_idno": {"note": "工作人员身份证号", "type": "string", "required": "true"},
        "client_cellphone": {"note": "客户手机号", "type": "string", "required": "true"},
        "client_name": {"note": "客户名称", "type": "string", "required": "true"},
        "order": {"note": "下单内容", "type": "string", "required": "true"},
        "time": {"note": "下单时间", "type": "date", "required": "true"},
        "deal": {"note": "核收金额", "type": "integer"},
        "dealnote": {"note": "核收备注", "type": "string"},
        "status_code": {"note": "工单状态", "type": "string", "required": "true"},
        "status_text": {"note": "", "type": "string", "required": "true"}
    },
    "ly0d10memo": {
        "_id": {"note": "客户工单 - 工作备忘", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d10unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "工作单位名称", "type": "string", "required": "true"},
        "id_business": {"note": "工单号", "type": "mongodb.id", "ref_tblName": "ly0d10business", "ref_fldName": "_id", "required": "true"},
        "memo": {"note": "备忘", "type": "string", "required": "true"},
        "time": {"note": "记录时间", "type": "date", "required": "true"},
        "recorder_cellphone": {"note": "记录员手机号", "type": "string", "required": "true"},
        "recorder_name": {"note": "记录员姓名", "type": "string", "required": "true"}
    },
    "ly0d10business0": {
        "_id": {"note": "巡检工单", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d10unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "工作单位名称", "type": "string", "required": "true"},
        "id_group": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d10group", "ref_fldName": "_id", "required": "true"},
        "group_name": {"note": "工作组名称", "type": "string", "required": "true"},
        "id_worker": {"note": "工作人员信息", "type": "mongodb.id", "ref_tblName": "ly0d10worker", "ref_fldName": "_id", "required": "true"},
        "worker_cellphone": {"note": "工作人员手机号", "type": "string", "required": "true"},
        "worker_name": {"note": "工作人员姓名", "type": "string", "required": "true"},
        "worker_idno": {"note": "工作人员身份证号", "type": "string", "required": "true"},
        "order": {"note": "下单内容", "type": "string", "required": "true"},
        "time": {"note": "下单时间", "type": "date", "required": "true"},
        "status_code": {"note": "工单状态", "type": "string", "required": "true"},
        "status_text": {"note": "", "type": "string", "required": "true"}
    },
    "ly0d10memo0": {
        "_id": {"note": "巡检工单 - 工作备忘", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d10unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "工作单位名称", "type": "string", "required": "true"},
        "id_business": {"note": "工单号", "type": "mongodb.id", "ref_tblName": "ly0d10business0", "ref_fldName": "_id", "required": "true"},
        "memo": {"note": "备忘", "type": "string", "required": "true"},
        "time": {"note": "记录时间", "type": "date", "required": "true"},
        "recorder_cellphone": {"note": "记录员手机号", "type": "string", "required": "true"},
        "recorder_name": {"note": "记录员姓名", "type": "string", "required": "true"},
        "photo": {"note": "现场照片", "type": "string"},
        "appendix": {"note": "附件", "type": "string"}
    }
}