export default {
    "ly0d9unit": {
        "_id": {"note": "物业单位信息", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "name": {"note": "名称", "type": "string", "required": "true"},
        "d11carwithin_self": {"note": "长期车自助缴费期限", "type": "integer"},
        "d11carwithin_termtype": {"note": "长期车自助缴费期限类型", "type": "string"},
        "d11carwithin_price": {"note": "长期车自助缴费单价", "type": "price"},
        "wx_appid": {"note": "微信支付 - APPID", "type": "string"},
        "wx_mchid": {"note": "微信商户号", "type": "string"},
        "smallticket": {"note": "小票机型号", "type": "string"}
    },
    "ly0d9reader": {
        "_id": {"note": "抄表员信息", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "物业单位名称", "type": "string", "required": "true"},
        "cellphone": {"note": "手机号", "type": "string", "required": "true"},
        "name": {"note": "姓名", "type": "string", "required": "true"}
    },
    "ly0d9position": {
        "_id": {"note": "物业分区", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "物业单位名称", "type": "string", "required": "true"},
        "text": {"note": "释义", "type": "string"}
    },
    "ly0d9sizetype": {
        "_id": {"note": "户型信息", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "物业单位名称", "type": "string", "required": "true"},
        "name": {"note": "户型名称", "type": "string", "required": "true"},
        "area_builtup": {"note": "建筑面积", "type": "string"},
        "area_usable": {"note": "使用面积", "type": "string"},
        "area": {"note": "计费面积", "type": "float", "required": "true"}
    },
    "ly0d9property": {
        "_id": {"note": "物业信息", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "物业单位名称", "type": "string", "required": "true"},
        "number": {"note": "户号", "type": "string", "required": "true"},
        "name": {"note": "户名", "type": "string"},
        "id_position": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9position", "ref_fldName": "_id"},
        "position_text": {"note": "物业分区", "type": "string"},
        "id_sizetype": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9sizetype", "ref_fldName": "_id"},
        "sizetype_name": {"note": "户型", "type": "string"},
        "area_builtup": {"note": "建筑面积", "type": "string"},
        "area_usable": {"note": "使用面积", "type": "string"},
        "area": {"note": "计费面积", "type": "float"},
        "owner_cellphone": {"note": "业主手机号", "type": "string"},
        "owner_name": {"note": "业主名称", "type": "string"},
        "id_business": {"note": "收费单号", "type": "mongodb.id", "ref_tblName": "ly0d9business", "ref_fldName": "_id"}
    },
    "ly0d9metername": {
        "_id": {"note": "抄表名称", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "物业单位名称", "type": "string", "required": "true"},
        "metername": {"note": "抄表名称", "type": "string", "required": "true"}
    },
    "ly0d9goods": {
        "_id": {"note": "服务类收费项目", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "物业单位名称", "type": "string", "required": "true"},
        "name": {"note": "项目名称", "type": "string", "required": "true"},
        "method_code": {"note": "计费方法", "type": "string", "required": "true"},
        "method_text": {"note": "", "type": "string", "required": "true"},
        "price": {"note": "单价", "type": "integer", "required": "true"},
        "self": {"note": "自助缴费期限", "type": "integer", "required": "true"}
    },
    "ly0d9goods0": {
        "_id": {"note": "资源类收费项目", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "物业单位名称", "type": "string", "required": "true"},
        "name": {"note": "项目名称", "type": "string", "required": "true"},
        "price": {"note": "单价", "type": "integer", "required": "true"},
        "self": {"note": "自助缴费额度", "type": "integer", "required": "true"},
        "self0": {"note": "预估使用天数", "type": "integer", "required": "true"},
        "id_metername": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9metername", "ref_fldName": "_id"},
        "metername": {"note": "抄表名称", "type": "string"}
    },
    "ly0d9business": {
        "_id": {"note": "收费单记录", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "物业单位名称", "type": "string", "required": "true"},
        "id_property": {"note": "物业信息", "type": "mongodb.id", "ref_tblName": "ly0d9property", "ref_fldName": "_id", "required": "true"},
        "property_number": {"note": "户号", "type": "string", "required": "true"},
        "property_name": {"note": "户名", "type": "string"},
        "time": {"note": "制单时间", "type": "date"},
        "amount_goods": {"note": "服务类项目计费", "type": "integer"},
        "amount_goods0": {"note": "资源类项目计费", "type": "integer"},
        "amount": {"note": "计费", "type": "integer"},
        "deal_goods": {"note": "服务类项目核收", "type": "integer"},
        "deal_goods0": {"note": "资源类项目核收", "type": "integer"},
        "deal": {"note": "核收", "type": "integer"}
    },
    "ly0d9meterrecord": {
        "_id": {"note": "抄表记录", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "物业单位名称", "type": "string", "required": "true"},
        "id_property": {"note": "物业信息", "type": "mongodb.id", "ref_tblName": "ly0d9property", "ref_fldName": "_id", "required": "true"},
        "property_number": {"note": "户号", "type": "string", "required": "true"},
        "property_name": {"note": "户名", "type": "string"},
        "id_metername": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9metername", "ref_fldName": "_id", "required": "true"},
        "metername": {"note": "抄表名称", "type": "string", "required": "true"},
        "readout": {"note": "抄表读数", "type": "float", "required": "true"},
        "time": {"note": "抄表时间", "type": "date", "required": "true"},
        "photo": {"note": "抄表照片", "type": "string"},
        "note": {"note": "备注", "type": "string"},
        "recorder_cellphone": {"note": "记录员手机号", "type": "string"},
        "recorder_name": {"note": "记录员姓名", "type": "string"},
        "id_business": {"note": "收费单号", "type": "mongodb.id", "ref_tblName": "ly0d9business", "ref_fldName": "_id"}
    },
    "ly0d9b_goods": {
        "_id": {"note": "收费记录：服务类项目", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "物业单位名称", "type": "string", "required": "true"},
        "id_property": {"note": "物业信息", "type": "mongodb.id", "ref_tblName": "ly0d9property", "ref_fldName": "_id", "required": "true"},
        "property_number": {"note": "户号", "type": "string", "required": "true"},
        "property_name": {"note": "户名", "type": "string"},
        "id_sizetype": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9sizetype", "ref_fldName": "_id"},
        "sizetype_name": {"note": "户型", "type": "string"},
        "area": {"note": "计费面积", "type": "float"},
        "id_goods": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9goods", "ref_fldName": "_id", "required": "true"},
        "goods_name": {"note": "收费项目", "type": "string", "required": "true"},
        "method_code": {"note": "计费方法", "type": "string", "required": "true"},
        "method_text": {"note": "", "type": "string", "required": "true"},
        "price": {"note": "单价", "type": "integer", "required": "true"},
        "from": {"note": "有效期：起", "type": "date", "required": "true"},
        "to": {"note": "有效期：止", "type": "date", "required": "true"},
        "amount": {"note": "计费", "type": "integer", "required": "true"},
        "time": {"note": "计费时间", "type": "date", "required": "true"},
        "deal": {"note": "核收", "type": "integer", "required": "true"},
        "dealnote": {"note": "核收备注", "type": "string"},
        "id_business": {"note": "收费单号", "type": "mongodb.id", "ref_tblName": "ly0d9business", "ref_fldName": "_id"}
    },
    "ly0d9b_goods0": {
        "_id": {"note": "收费记录：资源类项目", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "物业单位名称", "type": "string", "required": "true"},
        "id_property": {"note": "物业信息", "type": "mongodb.id", "ref_tblName": "ly0d9property", "ref_fldName": "_id", "required": "true"},
        "property_number": {"note": "户号", "type": "string", "required": "true"},
        "property_name": {"note": "户名", "type": "string"},
        "id_goods": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9goods0", "ref_fldName": "_id", "required": "true"},
        "goods_name": {"note": "收费项目", "type": "string", "required": "true"},
        "price": {"note": "单价", "type": "integer", "required": "true"},
        "count": {"note": "数量", "type": "float", "required": "true"},
        "amount": {"note": "计费", "type": "integer", "required": "true"},
        "time": {"note": "计费时间", "type": "date", "required": "true"},
        "deal": {"note": "核收", "type": "integer", "required": "true"},
        "dealnote": {"note": "核收备注", "type": "string"},
        "id_business": {"note": "收费单号", "type": "mongodb.id", "ref_tblName": "ly0d9business", "ref_fldName": "_id"}
    },
    "ly0d9memo": {
        "_id": {"note": "收费备忘", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d9unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "物业单位名称", "type": "string", "required": "true"},
        "id_property": {"note": "物业信息", "type": "mongodb.id", "ref_tblName": "ly0d9property", "ref_fldName": "_id", "required": "true"},
        "property_number": {"note": "户号", "type": "string", "required": "true"},
        "property_name": {"note": "户名", "type": "string"},
        "memo": {"note": "备忘", "type": "string", "required": "true"},
        "time": {"note": "记录时间", "type": "date", "required": "true"},
        "recorder_cellphone": {"note": "记录员手机号", "type": "string", "required": "true"},
        "recorder_name": {"note": "记录员姓名", "type": "string", "required": "true"},
        "id_business": {"note": "收费记录", "type": "mongodb.id", "ref_tblName": "ly0d9business", "ref_fldName": "_id"}
    }
}