export default {
    "ly0d8unit": {
        "_id": {"note": "库管单位", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "name": {"note": "库管单位名称", "type": "string", "required": "true"}
    },
    "ly0d8goodsgroup": {
        "_id": {"note": "货品分类", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "库管单位名称", "type": "string", "required": "true"},
        "text": {"note": "释义", "type": "string", "required": "true"}
    },
    "ly0d8goodsfrom": {
        "_id": {"note": "货品来源", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "库管单位名称", "type": "string", "required": "true"},
        "text": {"note": "释义", "type": "string", "required": "true"}
    },
    "ly0d8goodsto": {
        "_id": {"note": "货品去向", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "库管单位名称", "type": "string", "required": "true"},
        "text": {"note": "释义", "type": "string", "required": "true"}
    },
    "ly0d8goods": {
        "_id": {"note": "货品名录", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "库管单位名称", "type": "string", "required": "true"},
        "id_goodsgroup": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goodsgroup", "ref_fldName": "_id"},
        "goodsgroup_text": {"note": "货品分类", "type": "string"},
        "name": {"note": "货品名称", "type": "string", "required": "true"},
        "thumb": {"note": "图片", "type": "string"}
    },
    "ly0d8purchase": {
        "_id": {"note": "采购记录", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "库管单位名称", "type": "string", "required": "true"},
        "id_goods": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goods", "ref_fldName": "_id", "required": "true"},
        "goods_name": {"note": "货品名称", "type": "string", "required": "true"},
        "id_goodsgroup": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goodsgroup", "ref_fldName": "_id"},
        "goodsgroup_text": {"note": "货品分类", "type": "string"},
        "count": {"note": "数量", "type": "float", "required": "true"},
        "price": {"note": "采购单价", "type": "integer", "required": "true"},
        "time": {"note": "入库时间", "type": "date", "required": "true"},
        "id_goodsfrom": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goodsfrom", "ref_fldName": "_id"},
        "goodsfrom_text": {"note": "货品来源", "type": "string"},
        "keeper_cellphone": {"note": "库管人手机号", "type": "string", "required": "true"},
        "keeper_name": {"note": "库管人姓名", "type": "string", "required": "true"},
        "note": {"note": "备注", "type": "string"}
    },
    "ly0d8goodsin": {
        "_id": {"note": "入库记录", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "库管单位名称", "type": "string", "required": "true"},
        "id_goods": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goods", "ref_fldName": "_id", "required": "true"},
        "goods_name": {"note": "货品名称", "type": "string", "required": "true"},
        "id_goodsgroup": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goodsgroup", "ref_fldName": "_id"},
        "goodsgroup_text": {"note": "货品分类", "type": "string"},
        "count": {"note": "数量", "type": "float", "required": "true"},
        "time": {"note": "入库时间", "type": "date", "required": "true"},
        "id_goodsfrom": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goodsfrom", "ref_fldName": "_id"},
        "goodsfrom_text": {"note": "货品来源", "type": "string"},
        "keeper_cellphone": {"note": "库管人手机号", "type": "string", "required": "true"},
        "keeper_name": {"note": "库管人姓名", "type": "string", "required": "true"},
        "note": {"note": "备注", "type": "string"}
    },
    "ly0d8goodsout": {
        "_id": {"note": "出库记录", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "库管单位名称", "type": "string", "required": "true"},
        "id_goods": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goods", "ref_fldName": "_id", "required": "true"},
        "goods_name": {"note": "货品名称", "type": "string", "required": "true"},
        "id_goodsgroup": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goodsgroup", "ref_fldName": "_id"},
        "goodsgroup_text": {"note": "货品分类", "type": "string"},
        "count": {"note": "数量", "type": "float", "required": "true"},
        "time": {"note": "出库时间", "type": "date", "required": "true"},
        "id_goodsto": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goodsto", "ref_fldName": "_id"},
        "goodsto_text": {"note": "货品去向", "type": "string"},
        "keeper_cellphone": {"note": "库管人手机号", "type": "string", "required": "true"},
        "keeper_name": {"note": "库管人姓名", "type": "string", "required": "true"},
        "consignee_cellphone": {"note": "收货人手机号", "type": "string", "required": "true"},
        "consignee_name": {"note": "收货人姓名", "type": "string", "required": "true"},
        "note": {"note": "备注", "type": "string"}
    },
    "ly0d8sale": {
        "_id": {"note": "销售记录", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "库管单位名称", "type": "string", "required": "true"},
        "id_goods": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goods", "ref_fldName": "_id", "required": "true"},
        "goods_name": {"note": "货品名称", "type": "string", "required": "true"},
        "id_goodsgroup": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goodsgroup", "ref_fldName": "_id"},
        "goodsgroup_text": {"note": "货品分类", "type": "string"},
        "count": {"note": "数量", "type": "float", "required": "true"},
        "price": {"note": "销售单价", "type": "integer", "required": "true"},
        "time": {"note": "出库时间", "type": "date", "required": "true"},
        "id_goodsto": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goodsto", "ref_fldName": "_id"},
        "goodsto_text": {"note": "货品去向", "type": "string"},
        "keeper_cellphone": {"note": "库管人手机号", "type": "string", "required": "true"},
        "keeper_name": {"note": "库管人姓名", "type": "string", "required": "true"},
        "note": {"note": "备注", "type": "string"}
    },
    "ly0d8loss": {
        "_id": {"note": "库存核销", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_unit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8unit", "ref_fldName": "_id", "required": "true"},
        "unit_name": {"note": "库管单位名称", "type": "string", "required": "true"},
        "id_goods": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goods", "ref_fldName": "_id", "required": "true"},
        "goods_name": {"note": "货品名称", "type": "string", "required": "true"},
        "id_goodsgroup": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goodsgroup", "ref_fldName": "_id"},
        "goodsgroup_text": {"note": "货品分类", "type": "string"},
        "count": {"note": "数量", "type": "float", "required": "true"},
        "time": {"note": "核销时间", "type": "date", "required": "true"},
        "id_goodsto": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d8goodsto", "ref_fldName": "_id"},
        "goodsto_text": {"note": "货品去向", "type": "string"},
        "keeper_cellphone": {"note": "库管人手机号", "type": "string", "required": "true"},
        "keeper_name": {"note": "库管人姓名", "type": "string", "required": "true"},
        "note": {"note": "备注", "type": "string"}
    }
}