export default {
    "ly0d5restaurant": {
        "_id": {"note": "餐馆信息", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "name": {"note": "餐馆名称", "type": "string", "required": "true"},
        "smallticket": {"note": "小票机型号", "type": "string"},
        "wx_appid": {"note": "微信支付 - APPID", "type": "string"},
        "wx_mchid": {"note": "微信商户号", "type": "string"}
    },
    "ly0d5diningplace": {
        "_id": {"note": "用餐位置", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_restaurant": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5restaurant", "ref_fldName": "_id", "required": "true"},
        "restaurant_name": {"note": "餐馆名称", "type": "string", "required": "true"},
        "text": {"note": "释义", "type": "string"}
    },
    "ly0d5goodsgroup": {
        "_id": {"note": "菜品分类", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_restaurant": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5restaurant", "ref_fldName": "_id", "required": "true"},
        "restaurant_name": {"note": "餐馆名称", "type": "string", "required": "true"},
        "text": {"note": "释义", "type": "string"}
    },
    "ly0d5goods0group": {
        "_id": {"note": "配售商品分类", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_restaurant": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5restaurant", "ref_fldName": "_id", "required": "true"},
        "restaurant_name": {"note": "餐馆名称", "type": "string", "required": "true"},
        "text": {"note": "释义", "type": "string"}
    },
    "ly0d5table": {
        "_id": {"note": "用餐桌号", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_restaurant": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5restaurant", "ref_fldName": "_id", "required": "true"},
        "restaurant_name": {"note": "餐馆名称", "type": "string", "required": "true"},
        "tableno": {"note": "桌号", "type": "string", "required": "true"},
        "id_diningplace": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5diningplace", "ref_fldName": "_id"},
        "diningplace_text": {"note": "位置", "type": "string"},
        "status_code": {"note": "状态", "type": "string", "required": "true"},
        "status_text": {"note": "", "type": "string"},
        "id_business": {"note": "订单号", "type": "mongodb.id", "ref_tblName": "ly0d5business", "ref_fldName": "_id"}
    },
    "ly0d5goods": {
        "_id": {"note": "菜品", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_restaurant": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5restaurant", "ref_fldName": "_id", "required": "true"},
        "restaurant_name": {"note": "餐馆名称", "type": "string", "required": "true"},
        "id_goodsgroup": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5goodsgroup", "ref_fldName": "_id"},
        "goodsgroup_text": {"note": "分类", "type": "string"},
        "name": {"note": "菜品名称", "type": "string", "required": "true"},
        "price": {"note": "单价", "type": "integer", "required": "true"},
        "thumb": {"note": "图片", "type": "string"},
        "recommend": {"note": "推荐", "type": "boolean"}
    },
    "ly0d5goods0": {
        "_id": {"note": "配售商品", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_restaurant": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5restaurant", "ref_fldName": "_id", "required": "true"},
        "restaurant_name": {"note": "餐馆名称", "type": "string", "required": "true"},
        "id_goodsgroup": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5good0sgroup", "ref_fldName": "_id"},
        "goodsgroup_text": {"note": "分类", "type": "string"},
        "name": {"note": "商品名称", "type": "string", "required": "true"},
        "price": {"note": "单价", "type": "integer", "required": "true"},
        "thumb": {"note": "图片", "type": "string"}
    },
    "ly0d5goods1": {
        "_id": {"note": "损赔物品", "type": "mongodb.id", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_restaurant": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5restaurant", "ref_fldName": "_id", "required": "true"},
        "restaurant_name": {"note": "餐馆名称", "type": "string", "required": "true"},
        "name": {"note": "物品名称", "type": "string", "required": "true"},
        "price": {"note": "单价", "type": "integer", "required": "true"}
    },
    "ly0d5business": {
        "_id": {"note": "订单信息", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_restaurant": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5restaurant", "ref_fldName": "_id", "required": "true"},
        "restaurant_name": {"note": "餐馆名称", "type": "string", "required": "true"},
        "time": {"note": "用餐时间", "type": "date", "required": "true"},
        "peoples": {"note": "用餐人数", "type": "string"},
        "client_cellphone": {"note": "客户手机号", "type": "string"},
        "client_name": {"note": "客户名称", "type": "string"},
        "booknote": {"note": "预订说明", "type": "string"},
        "booktime": {"note": "预订时间", "type": "date"},
        "status_code": {"note": "订单状态", "type": "string", "required": "true"},
        "status_text": {"note": "", "type": "string"},
        "amount": {"note": "计费合计", "type": "integer"},
        "amount_b_goods": {"note": "菜金", "type": "integer"},
        "amount_b_goods0": {"note": "配售", "type": "integer"},
        "amount_b_goods1": {"note": "损赔", "type": "integer"},
        "deal": {"note": "核收", "type": "integer"},
        "dealnote": {"note": "核收备注", "type": "string"}
    },
    "ly0d5b_table": {
        "_id": {"note": "订单 - 用餐桌号", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_restaurant": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5restaurant", "ref_fldName": "_id", "required": "true"},
        "restaurant_name": {"note": "餐馆名称", "type": "string", "required": "true"},
        "id_business": {"note": "订单号", "type": "mongodb.id", "ref_tblName": "ly0d5business", "ref_fldName": "_id", "required": "true"},
        "id_diningplace": {"note": "餐位分区", "type": "mongodb.id", "ref_tblName": "ly0d5diningplace", "ref_fldName": "_id"},
        "diningplace_text": {"note": "", "type": "string"},
        "id_table": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5table", "ref_fldName": "_id"},
        "tableno": {"note": "餐位", "type": "string", "required": "true"}
    },
    "ly0d5b_goods": {
        "_id": {"note": "订单 - 菜品消费", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_restaurant": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5restaurant", "ref_fldName": "_id", "required": "true"},
        "restaurant_name": {"note": "餐馆名称", "type": "string", "required": "true"},
        "id_business": {"note": "订单号", "type": "mongodb.id", "ref_tblName": "ly0d5business", "ref_fldName": "_id", "required": "true"},
        "id_goodsgroup": {"note": "菜品分类", "type": "mongodb.id", "ref_tblName": "ly0d5goodsgroup", "ref_fldName": "_id"},
        "goodsgroup_text": {"note": "", "type": "string"},
        "id_goods": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5goods", "ref_fldName": "_id"},
        "name": {"note": "菜品名称", "type": "string", "required": "true"},
        "price": {"note": "单价", "type": "integer", "required": "true"},
        "count": {"note": "数量", "type": "float", "required": "true"}
    },
    "ly0d5b_goods0": {
        "_id": {"note": "订单 - 配售商品", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_restaurant": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5restaurant", "ref_fldName": "_id", "required": "true"},
        "restaurant_name": {"note": "餐馆名称", "type": "string", "required": "true"},
        "id_business": {"note": "订单号", "type": "mongodb.id", "ref_tblName": "ly0d5business", "ref_fldName": "_id", "required": "true"},
        "id_goodsgroup": {"note": "商品分类", "type": "mongodb.id", "ref_tblName": "ly0d5goods0group", "ref_fldName": "_id"},
        "goodsgroup_text": {"note": "", "type": "string"},
        "id_goods": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5goods0", "ref_fldName": "_id"},
        "name": {"note": "商品名称", "type": "string", "required": "true"},
        "price": {"note": "单价", "type": "integer", "required": "true"},
        "count": {"note": "数量", "type": "float", "required": "true"}
    },
    "ly0d5b_goods1": {
        "_id": {"note": "订单 - 损赔物品", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_restaurant": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5restaurant", "ref_fldName": "_id", "required": "true"},
        "restaurant_name": {"note": "餐馆名称", "type": "string", "required": "true"},
        "id_business": {"note": "订单号", "type": "mongodb.id", "ref_tblName": "ly0d5business", "ref_fldName": "_id", "required": "true"},
        "id_goods": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5goods1", "ref_fldName": "_id"},
        "name": {"note": "物品名称", "type": "string", "required": "true"},
        "price": {"note": "单价", "type": "integer", "required": "true"},
        "count": {"note": "数量", "type": "float", "required": "true"}
    },
    "ly0d5memo": {
        "_id": {"note": "订单备忘", "type": "mongodb.id", "required": "true"},
        "time_create": {"note": "创建时间", "type": "date", "required": "true"},
        "time_update": {"note": "更新时间", "type": "date", "required": "true"},
        "id_dataunit": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d0dataunit", "ref_fldName": "_id", "required": "true"},
        "dataunit_name": {"note": "", "type": "string", "required": "true"},
        "id_restaurant": {"note": "", "type": "mongodb.id", "ref_tblName": "ly0d5restaurant", "ref_fldName": "_id", "required": "true"},
        "restaurant_name": {"note": "餐馆名称", "type": "string", "required": "true"},
        "id_business": {"note": "订单号", "type": "mongodb.id", "ref_tblName": "ly0d5business", "ref_fldName": "_id", "required": "true"},
        "memo": {"note": "备忘", "type": "string", "required": "true"},
        "time": {"note": "记录时间", "type": "date", "required": "true"},
        "recorder_cellphone": {"note": "记录员手机号", "type": "string", "required": "true"},
        "recorder_name": {"note": "记录员姓名", "type": "string", "required": "true"}
    }
}